### PR TITLE
Merge the new docworker 

### PR DESCRIPTION
**Pull request by LibbyLi667**
merge the new docworker

### CODE REVIEW

**Comment by MarekSuchanek** [comment]
Thanks, I will take a look before the next release.

**Comment by MarekSuchanek** [comment]
Seems like a good thing to have. Do you plan to maintain https://github.com/UoA-eResearch/pandoc-docx-pagebreak-py? If not, I would fork it myself... or include directly.

I would prefer to have dependencies only from PyPI to avoid inconsistency/unavailability issues.

**Comment by neon-ninja** [comment]
Hi @MarekSuchanek,

Happy for you to integrate this in any way you see fit. https://github.com/UoA-eResearch/pandoc-docx-pagebreak-py has been relatively low maintenance so far - it's just been one commit last year to get it working for html input, and one commit today to make sure the version of panflute matches the version of pandoc used by document-worker (see the "Supported pandoc versions" section on https://pypi.org/project/panflute/). I do have a pending pull request at https://github.com/pandocker/pandoc-docx-pagebreak-py/pull/4, but it's unclear if that would ever get merged and make it to https://pypi.org/project/pandoc-docx-pagebreak/. We would fix https://github.com/UoA-eResearch/pandoc-docx-pagebreak-py if it were ever necessary, but we would likely only notice breaking changes when updating DSW, so there might be some lag time.

**Comment by MarekSuchanek** [comment]
Hello @neon-ninja,

Indeed the original repository seems unmaintained. So would this work for you?

- I will update `pandoc` and `wkhtmltopdf` that we use.
- I will include the project enhanced `pandoc-docx-pagebreak-py` directly (in terms of the LICENSE, there is no problem) in a way that we can add more easily in the future.


In case you need to improve it, you can propose changes directly to this repo and do not have keep https://github.com/UoA-eResearch/pandoc-docx-pagebreak-py

Also, in this way, we can "guarantee" that it is compatible and nothing "unwanted" gets into the worker, e.g., with some dependency update?

**Comment by neon-ninja** [comment]
Sounds good to me @MarekSuchanek 👍

**Comment by MarekSuchanek** [comment]
> Sounds good to me @MarekSuchanek 👍

@neon-ninja @LibbyLi667 please check #44

**Comment by neon-ninja** [comment]
Looks good to me @MarekSuchanek 👍

**Comment by MarekSuchanek** [comment]
OK, thanks, closing... done in #44

**Pull request closed without merging**
